In [15]:
# import modules and define functions
from pyscf import gto, scf
import pandas as pd
from scipy import linalg
import os
os.environ['OMP_NUM_THREADS'] = "1" 

In [3]:
# build H2 with minimal basis
atom = 'H 0 0 0; H 0 0 0.74'
basis = 'sto-3g'
h2_0_1 = gto.Mole()
h2_0_1.build(atom=atom,basis=basis,charge=0,spin=0)

In [24]:
# SCF calculations
# HF
h2_0_1_rhf = scf.RHF(h2_0_1).run()

converged SCF energy = -1.11675930739643


In [109]:
# get the density matrix and the matrix elements
rho = h2_0_1_rhf.make_rdm1()
j, k = h2_0_1_rhf.get_jk()
h = h2_0_1_rhf.get_hcore()
f = h2_0_1_rhf.get_fock()

In [114]:
# get H and G
H = np.dot(rho, h) * 2 # 2*h_11
J = np.dot(rho, j)
K = np.dot(rho, k)

In [120]:
H+2*J-K

array([[-1.15710772, -1.15710772],
       [-1.15710772, -1.15710772]])

In [106]:
K

array([[1.34951185, 1.34951185],
       [1.34951185, 1.34951185]])

In [108]:
h2_0_1_rhf.analyze(verbose=5)

**** SCF Summaries ****
Total Energy =                          -1.116759307396426
Nuclear Repulsion Energy =               0.715104339081081
One-electron Energy =                   -2.506619573291955
Two-electron Energy =                    0.674755926814449
**** MO energy ****
MO #1   energy= -0.578553859831529 occ= 2
MO #2   energy= 0.671143491914254  occ= 0
 ** MO coefficients (expansion on meta-Lowdin AOs) **
               #1        #2       
  0 H 1s       0.70711   0.70711
  1 H 1s       0.70711  -0.70711
 ** Mulliken pop on meta-lowdin orthogonal AOs  **
 ** Mulliken pop  **
pop of  0 H 1s        1.00000
pop of  1 H 1s        1.00000
 ** Mulliken atomic charges  **
charge of  0H =      0.00000
charge of  1H =     -0.00000
Dipole moment(X, Y, Z, Debye):  0.00000,  0.00000, -0.00000


((array([1., 1.]), array([ 4.44089210e-16, -2.22044605e-16])),
 array([ 0.00000000e+00,  0.00000000e+00, -2.25752431e-15]))